# Experimental Design Space Configuration
# Define your experiment matrix here

# LLM Configurations to test
llm_configurations:
  qwen_local:
    model: "qwen2.5-coder:32B"
    url: "https://chat.binghamton.edu/api/chat/completions"
    api_key: "sk-571df6eec7f5495faef553ab5cb2c67a"
    
  # Uncomment and configure additional LLMs as needed
  # gpt4:
  #   model: "gpt-4"
  #   url: "https://api.openai.com/v1/chat/completions"
  #   api_key: "your-openai-key-here"
  #   
  # claude_sonnet:
  #   model: "claude-3-sonnet-20240229"
  #   url: "https://api.anthropic.com/v1/messages"
  #   api_key: "your-anthropic-key-here"
  #
  # gpt35:
  #   model: "gpt-3.5-turbo"
  #   url: "https://api.openai.com/v1/chat/completions"
  #   api_key: "your-openai-key-here"

# Agent Types to test
agent_types:
  - standard    # Standard LLM agents
  - memory      # Memory-enhanced agents

# Social Scenarios to test
scenarios:
  - baseline
  - race_white_black
  - ethnic_asian_hispanic
  - economic_high_working
  - political_liberal_conservative

# Grid Configurations to test
grid_configurations:
  small:
    grid_size: 10
    type_a: 25
    type_b: 25
  medium:
    grid_size: 15
    type_a: 75
    type_b: 75
  large:
    grid_size: 20
    type_a: 150
    type_b: 150
  # xlarge:
  #   grid_size: 25
  #   type_a: 200
  #   type_b: 200

# Experiment Parameters
experiment_parameters:
  runs_per_config: 20        # Number of runs per configuration
  max_steps: 1000           # Maximum steps per simulation
  use_llm_probability: 1.0  # Probability of using LLM (1.0 = always)

# Quick Test Mode (for development)
quick_test:
  enabled: false
  runs_per_config: 3
  max_steps: 100
  grids: ["small"]
  scenarios: ["baseline"]