#!/usr/bin/env python3
"""Derive the SAMPLED sanity-check configs for the five segregating models.

    python configs/make_sanity_configs.py            # write/refresh all
    python configs/make_sanity_configs.py --dry-run

WHY THIS EXISTS (user request 2026-09-07)
The production result set is built from the EXACT (log-probability) value
functions in value_functions/results/llm_logprob/. The sampled route was
closed on 2026-09-06 because llama-server returns batch-dependent
probabilities at concurrency > 1, so the -vf-r3 tables are not a result.
This generates a small SAMPLED arm purely as a cross-check on the exact
tables: does independently sampling the same cells reproduce the same
scenario ordering?

Two deliberate differences from the retired -vf-r3 campaign:

  concurrency: 1   The batch-numerics probes measured sequential extraction as
                   bit-reproducible (sequential_max_range = 0.000 for every
                   model) while concurrency 4 spans up to 0.95 in probability
                   on gemma. Sampling concurrently would re-measure that
                   artifact instead of testing the exact tables, which defeats
                   the point of the check.
  samples: 100     Raised from 25 on 2026-09-07 (user decision). 100 is the
                   SAME n the retired concurrency-4 campaign used, which makes
                   this arm that campaign's exact sequential counterfactual:
                   any difference is the batch-numerics artifact, with no
                   sample-size confound. Wilson 95% half-width at p=0.5 is
                   +/-0.094 (vs +/-0.170 at n=25). Cost, from measured
                   sequential latency (qwen 590 ms, gemma 654, hermes 785,
                   llama 1065, deepseek 1149 ms/request; 540 cells/model):
                   ~64 h for the five models, ~2.7 days.

Artifacts land in value_functions/results/sampled_small/ under the
label suffix -sanity, and simulations use llm_model <model>-vf-s, so nothing
here can be confused with either the exact (-vf-lp) or retired sampled
(-vf-r3) sets in any run folder, figure or roll-up.

Run them with:  ./run_sanity_vf_chain.sh
"""
import argparse
import re
from pathlib import Path

CONFIGS = Path(__file__).resolve().parent

# The models whose DI rises meaningfully above the chance floor (user decision
# 2026-09-07). granite, mistral and phi-4 sit on the 0.125 floor in every
# scenario, so a sampled-vs-exact ordering check there would compare two flat
# lines. olmo2 was added on 2026-09-07: it is outside the main model set but is
# in fact the STRONGEST segregator measured (DI 0.458-0.738 vs hermes' 0.484
# ceiling), so "we cross-checked the segregating models" would not hold without
# it.
KEYS = ["qwen", "gemma", "hermes", "llama", "deepseek", "olmo2"]

SANITY_STORE = "value_functions/results/sampled_small"           # build out_dir
SANITY_TABLES = f"{SANITY_STORE}/tables"                          # what runs load
SAMPLES = 100
CONCURRENCY = 1
RUNS = 10

BUILD_HEADER = (
    "# =============================================================================\n"
    "# SANITY-CHECK sampling arm — generated by configs/make_sanity_configs.py;\n"
    "# do not edit by hand. Differs from the production sampling yaml ONLY in\n"
    f"# concurrency ({CONCURRENCY}, sequential: the batch-numerics artifact is not\n"
    f"# reproduced), sampling.samples ({SAMPLES}), label (-sanity) and out_dir.\n"
    "# =============================================================================\n"
)

RUN_HEADER = (
    "# =============================================================================\n"
    "# SANITY-CHECK simulation run — generated by configs/make_sanity_configs.py;\n"
    "# do not edit by hand. Differs from the _lp yaml ONLY in value_function (the\n"
    f"# sequentially sampled -sanity tables), llm_model (-vf-s) and runs ({RUNS}).\n"
    "# Read against the -vf-lp exact results, not as a result in its own right.\n"
    "# =============================================================================\n"
)


def strip_first_banner(text):
    return text.replace(
        "# =============================================================================\n", "", 1)


def make_build_config(text):
    text = re.sub(r'^label: "?([^"\n]+?)"?\s*$',
                  lambda m: f'label: {m.group(1)}-sanity', text, count=1, flags=re.M)
    text = re.sub(r'^concurrency: .*$', f'concurrency: {CONCURRENCY}'
                  '          # SEQUENTIAL: do not reproduce the batch-numerics artifact',
                  text, count=1, flags=re.M)
    text = re.sub(r'^(\s+)samples: \d+\s*$', rf'\g<1>samples: {SAMPLES}', text, count=1, flags=re.M)
    text = re.sub(r'^out_dir: .*$', f'out_dir: {SANITY_STORE}', text, count=1, flags=re.M)
    return BUILD_HEADER + strip_first_banner(text)


def make_run_config(text):
    # Source is the canonical _lp yaml (2026-09-07; the _r3 lineage is retired):
    # its value_function is the exact table under llm_logprob/tables/vf_<label>-lp__…
    # and its llm_model is <model>-vf-lp.
    text = re.sub(
        r'value_function: "value_functions/results/llm_logprob/tables/vf_([^_"]+(?:-[^_"]+)*)-lp__\{scenario\}__(\w+)\.json"',
        lambda m: f'value_function: "{SANITY_TABLES}/vf_{m.group(1)}-sanity__{{scenario}}__{m.group(2)}.json"',
        text)
    text = re.sub(r'(llm_model: "[^"]*?)-vf-lp"', r'\1-vf-s"', text)
    text = re.sub(r'(llm_model: )([a-z0-9.\-]+)-vf-lp\b', r'\1\2-vf-s', text)
    # Only the production run count (10,000) is scaled down. The smoke_test
    # profile keeps its 2 runs x 2 steps gate (user directive): rewriting it
    # would turn a 20-second launch check into a real batch.
    text = re.sub(r'^(\s+)runs: 10000\s*$', rf'\g<1>runs: {RUNS}', text, flags=re.M)
    text = re.sub(r'^skip_vf_build: .*$', 'skip_vf_build: true', text, count=1, flags=re.M)
    # Drop the _lp yaml's own "hand-edited source" note: this file is generated.
    text = re.sub(r'^# EXACT-table run \(logprob value functions.*?\(no ruler\)\.\n', '',
                  text, count=1, flags=re.M | re.S)
    return RUN_HEADER + strip_first_banner(text)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    for key in KEYS:
        for src_name, dst_name, convert in (
            (f"value_function_scenarios_{key}.yaml",
             f"value_function_scenarios_{key}_sanity.yaml", make_build_config),
            (f"vf_run_{key}_lp.yaml", f"vf_run_{key}_sanity.yaml", make_run_config),
        ):
            src = CONFIGS / src_name
            if not src.exists():
                print(f"SKIP {src_name}: missing")
                continue
            out = convert(src.read_text())
            if args.dry_run:
                print(f"--- {dst_name} ---")
                print(out[:400])
            else:
                (CONFIGS / dst_name).write_text(out)
                print(f"wrote {dst_name}")


if __name__ == "__main__":
    main()
