run_root: value_functions/results/date_sensitivity/mistral/simulations/2024-01-01
run_id: null
llm_model: mistral-small-4-119b-vf-lp-d20240101
manifest_file: null
skip_vf_build: true
skip_contexts: false
skip_analysis: false
continue_on_error: false
dry_run: false
vf_build_args:
  config: configs/value_function_scenarios_mistral.yaml
  plot: true
contexts_args: &id001
  scenarios:
  - baseline
  - race_white_black
  - ethnic_asian_hispanic
  - income_high_low
  - political_liberal_conservative
  - green_yellow
  runs: 1000
  max_steps: 1000
  grid_size: 20
  num_type_a: 160
  num_type_b: 160
  value_function: value_functions/results/date_sensitivity/mistral/tables/2024-01-01/tables/vf_mistral-small-4-119b-chat-grammar-d20240101-lp__{scenario}__R3_dual_count.json
  temperature: 0.3
  scenario_file: scenarios_a2.py
  llm_model: mistral-small-4-119b-vf-lp-d20240101
  processes: 15
  no_parallel: false
  new: true
analysis_args: {}
skip_cross_model: true
profiles:
  production:
    contexts_args: *id001
